### PR TITLE
Rms suggested changes

### PR DESCRIPTION
**Pull request by dstopp**
**Summary***
•	Made the nav bar static
•	Added a gray bar below the nav bar to allow for some visual differentiation between the nav and site contents
•	Moved the information (i) icon and the dropdown/dropup arrows closer to the associated element so the association was more specific and obvious
•	Added a ‘hover’ ability, such that when the mouse pointer object hovers over the “Find a Node” element, the menu will drop down.  The menu will collapse when the mouse pointer object hovers out of the menu area
•	Clicking on the up/down arrow will expand/collapse the menu
•	Menu items are now left aligned for a cleaner visual interface
•	When a node is selected, the menu on the original page collapses and the selected node is unhighlighted, leaving the menu back in its original default state
•	Removed the outlines when you click on the (i) icon and additional menu elements, as they were visually distracting and not consistent among all the different browsers and in some cases the outline was partially obscured by the dropdown.
•	Updated the up/down keyboard function so that it works when the user has clicked on the nav.

**Test Data and/or Report**
I tested 28 different browser combinations, both before and after I updated the code.  As it is 100% gui, I did not create a regression test for it.

**Related Issues**
n/a

### CODE REVIEW

**Comment by jordanpadams** [comment]
@c-suh can we deploy this on pds-gamma to test it out?

**Comment by jordanpadams** [comment]
Refs #25

**Comment by jordanpadams** [comment]
@c-suh see above. if we could deploy this on pds-gamma for testing, that would be great

**Review by c-suh — COMMENTED** [review]
@dstopp thank you for your input and work and the thorough testing! There are a number of small items to address, and I thought it quicker and more clear to create a separate branch from this repository instead of requiring a review of my review.

I have tried to find the balance between incorporating as many of your changes as possible while retaining the practices that we know to be amenable to the websites which already have the PDS app bar installed. I will mention you in the new PR so that you will have a link to test the changes. Thank you!

**Comment by jordanpadams** [comment]
closing for #26

**Pull request closed without merging**
